--- #Build Base-AMI Ubuntu Trusty 16.04 in region
- name: Get Infra Stack facts
  cloudformation_facts:
    stack_name: "{{ infra_stack_name }}"
    stack_resources: true
    region: "{{ region }}"
- name: Check for Source AMI
  fail: msg="Source AMI not found"
  failed_when: not (source_ami is defined and source_ami)
- name: Create {{ service }} AMI
  shell: >
    packer build \
          -var "source_ami={{ source_ami }}" \
          -var "region={{ region }}" \
          -var "vpc_id={{ cloudformation[infra_stack_name].stack_outputs.VPCid }}" \
          -var "subnet_id={{ cloudformation[infra_stack_name].stack_outputs.Pubsubnetid1 }}" \
          -var "service_name={{ service_name }}" \
          -var "service={{ service }}" \
          {{wrk_home}}/services/{{ service }}/{{ service }}_ami.json
  # args:
  #   chdir: playbooks/services/{{ service }}/
  register: packer
- name: Display packer output
  debug: var=packer
