---
- name: Default base
  hosts: all
  connection: local
  gather_facts: false
  become: true
  pre_tasks:
    - name: Remove any Apt Locks
      raw: sudo rm /var/lib/apt/lists/lock; sudo rm /var/cache/apt/archives/lock; sudo rm /var/lib/dpkg/lock
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (sudo apt -y update && apt install -y python-minimal)
      register: output
      changed_when: output.stdout != ""
  roles:
    - common
    - cleanup
