---
- name: Add ansible ppa
  apt_repository:
    repo: ppa:ansible/ansible

- name: Update apt repos.
  apt:
    update_cache: yes
  tags: common

- name: Upgrade distribution
  apt:
    upgrade: yes
  tags: common

- name: Upgrade distribution
  apt:
    name: "*"
    state: latest
    force_apt_get: yes
  tags: common

- name: Install common apt packages.
  apt: name={{ item }}
  loop:
    - python3-netaddr
    - python3-dev
    - python3-pip
    - python-netaddr
    - python-dev
    - python-pip
    - ansible
    - unzip
    - python-requests
    - iftop
    - sysstat
    - jq
    - htop
    - wget
    - curl
    - vim
    - git
    - nfs-client
    - cifs-utils
    - tcsh
    - xrdp
    - xfce4
    - mailutils
    - mosh
  tags: common
