---

- name: Update and install Apt packages
  include: apt_update_install.yml

- name: Install Pip packages
  include: install_pip.yml

- name: Disable UFW
  include: disable_ufw.yml

- name: Disable IP6
  include: disable_ip6.yml

- name: Make VIM Default editor
  include: vim_default.yml

- name: Adding sudoers file
  include: sudoers_file.yml

- name: Modifying SSHD
  include: sshd_modify.yml

- name: Adding IT_Standards file.
  include: it_standards.yml
